### ISSUE TITLE
Export to various formats from WikiSuite (milestone 3b)

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/timesheets#31]
See https://github.com/federatedbookkeeping/timesheets#milestone-3-wikisuite

**Comment by kroky** [comment]
Export to timeld.org gateway via tabular 11 works now: https://timesheet.dev3.evoludata.com/tiki-tabular-list?tabularId=11

**Comment by Angus-McAllister** [comment]
Also super news!  I'll check that I can see the Tiki data in timeld.

**Comment by kroky** [comment]
Milestone 3b has been completed. Demonstration could be done via 2 ways:
1. Install Tiki (https://tiki.org/Get-Tiki), Install Timesheets profile (https://profiles.tiki.org/Timesheets), configure DSN/Content authentication with your credentials for pondersource and timeld. Configure tabular formats for Mite, Scoro and Time with proper API endpoints depending on your accounts in these 3rd parties. Add local Tiki users for all the users you plan to enter/export data for.
2. This is what has been done in https://timesheet.dev3.evoludata.com - you can register and use the existing tabular formats there.

Usage:
1. manual export using Export button in existing tabulars in the following formats:
  1.1. https://timesheet.dev3.evoludata.com/tiki-tabular-list?tabularId=6 - Full format using the WikiSuite/Tiki timesheet format.
  1.2. https://timesheet.dev3.evoludata.com/tiki-tabular-list?tabularId=7 - csv format for importing into Time app
  1.3. https://timesheet.dev3.evoludata.com/tiki-tabular-list?tabularId=8 - json format using the Scoro API
  1.4. https://timesheet.dev3.evoludata.com/tiki-tabular-list?tabularId=9 - json format using the Mite API
  1.5. https://timesheet.dev3.evoludata.com/tiki-tabular-list?tabularId=10 - json format using the Pondersource/Prejournal API
  1.6. https://timesheet.dev3.evoludata.com/tiki-tabular-list?tabularId=11 - ndjson format using the timeld API
  1.7. https://timesheet.dev3.evoludata.com/tiki-tabular-list?tabularId=12 - iCal/ics format for calendar synchronization
2. automated export using Tiki Scheduler - a job could be scheduled to run on a specific interval and does the export in an automated way. Some exports require parameters which should be specified on the command line. Only API exports are supported this way, otherwise, we end up producing a single csv or json file with the export.
